spring:
  datasource:
    username: ${MySQL.username}
    password: ${MySQL.password}
    url: ${MySQL.url}
  flyway:
    enabled: false
    out-of-order: true

logging:
  level:
    com.ebay.dap.epic.tdq: debug
    org.springframework.security: debug
    com.baomidou.mybatisplus: debug

global:
  web:
    security:
      enabled: false


pronto:
  scheme: https
  hostname: estess762test-dataslc.stratus.qa.ebay.com
  port: 443
  api-key: _TDQ_SVC_USER
  api-value: anGp2222anGp2222$