spring:
  datasource:
    username: ${MySQL.username}
    password: ${MySQL.password}
    url: ${MySQL.url}
  flyway:
    enabled: false
    out-of-order: true

logging:
  level:
    com.ebay.dap.epic.tdq: debug
    org.springframework.security: debug
    com.baomidou.mybatisplus: debug

global:
  web:
    security:
      enabled: false


pronto:
  scheme: https
  hostname: estdq-datalvs.vip.ebay.com
  port: 443
  username: ${pronto.username}
  password: ${pronto.password}