spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
    time-zone: UTC
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximumPoolSize: 10
      connection-timeout: 15000
      validation-timeout: 5000
  flyway:
    enabled: true
    clean-disabled: true
    baseline-version: 0
    baseline-on-migrate: true
    out-of-order: false
    validate-on-migrate: true
    validate-migration-naming: true
  task:
    scheduling:
      pool:
        size: 10
      shutdown:
        await-termination: true
        await-termination-period: 10m

smtp:
  internal:
    host: mxrc.vip.ebay.com
    port: 25
  external:
    host: mx.vip.ebay.com
    port: 25

mybatis-plus:
  #  typeEnumsPackage: com.ebay.dap.epic.tdq.data.enums
  typeHandlersPackage: com.ebay.dap.epic.tdq.data.handler
  configuration:
    mapUnderscoreToCamelCase: true

server:
  error:
    whitelabel:
      enabled: false
    include-exception: true
    include-message: always
    include-stacktrace: never
    include-binding-errors: always

global:
  web:
    security:
      enabled: false

pronto:
  scheme: https
  hostname: estdq-datalvs.vip.ebay.com
  port: 443
  username: ${PRONTO_USERNAME}
  password: ${PRONTO_PASSWORD}

springdoc:
  packagesToScan: com.ebay.dap.epic.tdq.web.controller
  pathsToMatch: /api/**
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
  show-actuator: true

mmd-common-cfg:
  # url: http://10.78.235.92/mmd/find-anomaly
  #http://mmd-ng-pp-svc.mmd-prod-ns.svc.25.tess.io:8848/mmd/find-anomaly
  url: https://mmd.dss.vip.ebay.com/api/mmd/find-anomaly
  head-params:
    BI_CLIENT_APP_ID: TDQ_hourly
    BI_CLIENT_APP_KEY: tdQ_MMD_AweS0ME
  global-config:
    client-app-domain-id: Buyer Growth (or any other domain/team)
    model-type: burst
    noise-removal: true
  job-param:
    id: 0
    label: Here are some descriptions of your job

notification:
  email:
    enabled: true
    to: DL-eBay-Tracking-Data-Quality@ebay.com
    cc: DL-eBay-Tracking-Behavior-Data@ebay.com

management:
  endpoints:
    web:
      exposure:
        include: env